<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            /*--- fruits ---*/
            [
                'id' => 1,
                'name' => 'Bananas',
                'thumbnail' => 'fruits-1.jpg',
                'description' => 'bunch of 5',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 2,
                'name' => 'Avocado',
                'thumbnail' => 'fruits-2.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 3,
                'name' => 'Blueberries',
                'thumbnail' => 'fruits-3.jpg',
                'description' => '125g',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 20,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 4,
                'name' => 'Oranges',
                'thumbnail' => 'fruits-4.jpg',
                'description' => '4 units',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 23,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 5,
                'name' => 'Kiwi',
                'thumbnail' => 'fruits-5.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 14,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 6,
                'name' => 'Apples',
                'thumbnail' => 'fruits-6.jpg',
                'description' => '6 units',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 12,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 7,
                'name' => 'Limes',
                'thumbnail' => 'fruits-7.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 13,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 8,
                'name' => 'Pomegranate',
                'thumbnail' => 'fruits-8.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 9,
                'name' => 'Mango',
                'thumbnail' => 'fruits-9.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 10,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 10,
                'name' => 'Pineapple',
                'thumbnail' => 'fruits-10.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 21,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 11,
                'name' => 'Pears',
                'thumbnail' => 'fruits-11.jpg',
                'description' => '1 kg',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 22,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 12,
                'name' => 'Sweetcorn',
                'thumbnail' => 'fruits-12.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 16,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 13,
                'name' => 'Lemons',
                'thumbnail' => 'fruits-13.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 7,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 14,
                'name' => 'Watermelon',
                'thumbnail' => 'fruits-15.jpg',
                'description' => 'each',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 30,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 15,
                'name' => 'Cherry',
                'thumbnail' => 'fruits-15.jpg',
                'description' => '250g',
                'category_id' => 11,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            /*--- end-fruits ---*/

            /*--- vegetables ---*/
            [
                'id' => 16,
                'name' => 'Celery',
                'thumbnail' => 'vegetable-1.jpg',
                'description' => '250g',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 17,
                'name' => 'Broccoli',
                'thumbnail' => 'vegetable-2.jpg',
                'description' => '250g',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 18,
                'name' => 'Carrots',
                'thumbnail' => 'vegetable-3.jpg',
                'description' => '750g',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 19,
                'name' => 'Aubergine',
                'thumbnail' => 'vegetable-4.jpg',
                'description' => 'each',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 23,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 20,
                'name' => 'Cucumber',
                'thumbnail' => 'vegetable-5.jpg',
                'description' => '250g',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 21,
                'name' => 'Spring Onions',
                'thumbnail' => 'vegetable-6.jpg',
                'description' => 'bunch',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 12,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 22,
                'name' => 'Tundra Cabbage',
                'thumbnail' => 'vegetable-7.jpg',
                'description' => 'each',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 12,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 23,
                'name' => 'Cherry Tomatoes',
                'thumbnail' => 'vegetable-8.jpg',
                'description' => '250g',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ], [
                'id' => 24,
                'name' => 'Spinach',
                'thumbnail' => 'vegetable-9.jpg',
                'description' => '300g',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 10,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 25,
                'name' => 'Little Gem Lettuce',
                'thumbnail' => 'vegetable-10.jpg',
                'description' => '2 packs',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 13,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 26,
                'name' => 'Shiitake Mushrooms',
                'thumbnail' => 'vegetable-11.jpg',
                'description' => '200g',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 22,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 27,
                'name' => 'White Mushrooms',
                'thumbnail' => 'vegetable-12.jpg',
                'description' => '200g',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 28,
                'name' => 'French Beans',
                'thumbnail' => 'vegetable-13.jpg',
                'description' => '250g',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 7,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 29,
                'name' => 'Fennel',
                'thumbnail' => 'vegetable-14.jpg',
                'description' => 'each',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 3,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 30,
                'name' => 'Potatoes',
                'thumbnail' => 'vegetable-15.jpg',
                'description' => '1.5kg',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            /*--- end-vegetables ---*/

            /*--- meat ---*/
            [
                'id' => 31,
                'name' => 'Whole Chicken',
                'thumbnail' => 'meat-1.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 9,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 32,
                'name' => 'Beef Top Sirloin Steak',
                'thumbnail' => 'meat-2.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 8,
                'discount_id' => null,
                'price' => 30,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 33,
                'name' => 'Fresh Pork Neck Steaks',
                'thumbnail' => 'meat-3.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 7,
                'discount_id' => null,
                'price' => 35,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 34,
                'name' => 'Beef Arm Chuck Roast',
                'thumbnail' => 'meat-4.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 8,
                'discount_id' => null,
                'price' => 46,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 35,
                'name' => 'Fresh Chicken Drumsticks',
                'thumbnail' => 'meat-5.jpg',
                'description' => 'Leg And Drum Sticks',
                'category_id' => 9,
                'discount_id' => null,
                'price' => 20,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 36,
                'name' => 'Beef Striploin Steak',
                'thumbnail' => 'meat-6.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 8,
                'discount_id' => null,
                'price' => 35,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 37,
                'name' => 'Boneless Pork Shoulder',
                'thumbnail' => 'meat-7.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 7,
                'discount_id' => null,
                'price' => 30,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 38,
                'name' => 'Raw Pork Ribs',
                'thumbnail' => 'meat-8.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 7,
                'discount_id' => null,
                'price' => 27,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 39,
                'name' => 'Beef Chuck Center Roast',
                'thumbnail' => 'meat-9.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 8,
                'discount_id' => null,
                'price' => 38,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 40,
                'name' => 'Chicken Feet & Paws',
                'thumbnail' => 'meat-10.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 9,
                'discount_id' => null,
                'price' => 22,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 41,
                'name' => 'Beef T-bone Steak',
                'thumbnail' => 'meat-11.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 8,
                'discount_id' => null,
                'price' => 32,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 42,
                'name' => 'Beef Blade Chuck Steak',
                'thumbnail' => 'meat-12.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 8,
                'discount_id' => null,
                'price' => 32,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 43,
                'name' => 'Beef Hind Shank Steak',
                'thumbnail' => 'meat-13.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 8,
                'discount_id' => null,
                'price' => 30,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 44,
                'name' => 'Berkshire Pork Belly',
                'thumbnail' => 'meat-14.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 7,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 45,
                'name' => 'Chicken Breast Inner Fillet',
                'thumbnail' => 'meat-15.jpg',
                'description' => '10/15/20 kg',
                'category_id' => 9,
                'discount_id' => null,
                'price' => 12,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            /*--- end-meats ---*/

            /*--- milks ---*/
            [
                'id' => 46,
                'name' => 'Goat Cheese',
                'thumbnail' => 'milk-1.jpg',
                'description' => 'cheese',
                'category_id' => 10,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 47,
                'name' => 'Sour Milk',
                'thumbnail' => 'milk-2.jpg',
                'description' => 'milk',
                'category_id' => 10,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 48,
                'name' => 'Fresh Milk',
                'thumbnail' => 'milk-3.jpg',
                'description' => 'milk',
                'category_id' => 10,
                'discount_id' => null,
                'price' => 20,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 49,
                'name' => 'Butter',
                'thumbnail' => 'milk-4.jpg',
                'description' => 'butter',
                'category_id' => 10,
                'discount_id' => null,
                'price' => 12,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 50,
                'name' => 'Fruit Yogurt',
                'thumbnail' => 'milk-5.jpg',
                'description' => 'yogurt',
                'category_id' => 10,
                'discount_id' => null,
                'price' => 18,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 51,
                'name' => 'Milk Coffee',
                'thumbnail' => 'milk-6.jpg',
                'description' => 'coffee',
                'category_id' => 10,
                'discount_id' => null,
                'price' => 12,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 52,
                'name' => 'Cow Cheese',
                'thumbnail' => 'milk-7.jpg',
                'description' => 'cheese',
                'category_id' => 10,
                'discount_id' => null,
                'price' => 24,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            [
                'id' => 53,
                'name' => 'Kefir',
                'thumbnail' => 'milk-8.jpg',
                'description' => 'Popularly, however, the term is restricted to the ripened ovaries that are sweet and either succulent or pulpy. For treatment of the cultivation of fruits, see fruit farming. For treatment of the nutrient composition and processing of fruits, see fruit processing.',
                'category_id' => 10,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-03-07 21:25:42',
                'updated_at' => '2022-03-07 21:25:42',
            ],
            /*--- end-milks ---*/
            /*--- More product ---*/
            [
                'id' => 54,
                'name' => 'Bananas Usa',
                'thumbnail' => 'fruits-1.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 18,
                'status' => 1,
                'created_at' => '2022-02-07 21:25:42',
                'updated_at' => '2022-02-07 21:25:42',
            ],
            [
                'id' => 55,
                'name' => 'Bananas China',
                'thumbnail' => 'fruits-2.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 10,
                'status' => 1,
                'created_at' => '2022-02-07 11:25:42',
                'updated_at' => '2022-02-07 11:25:42',
            ],
            [
                'id' => 56,
                'name' => 'Strawberry Usa',
                'thumbnail' => 'fruits-3.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 14,
                'status' => 1,
                'created_at' => '2022-02-07 11:11:42',
                'updated_at' => '2022-02-07 11:11:42',
            ],
            [
                'id' => 57,
                'name' => 'Strawberry China',
                'thumbnail' => 'fruits-4.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 19,
                'status' => 1,
                'created_at' => '2022-02-07 11:22:33',
                'updated_at' => '2022-02-07 11:22:33',
            ],
            [
                'id' => 58,
                'name' => 'Strawberry Italia',
                'thumbnail' => 'fruits-5.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 22,
                'status' => 1,
                'created_at' => '2021-02-07 11:22:33',
                'updated_at' => '2021-02-07 11:22:33',
            ],
            [
                'id' => 59,
                'name' => 'Grape Italia',
                'thumbnail' => 'fruits-6.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 23,
                'status' => 1,
                'created_at' => '2021-11-07 11:22:33',
                'updated_at' => '2021-11-07 11:22:33',
            ],
            [
                'id' => 60,
                'name' => 'Grape China',
                'thumbnail' => 'fruits-7.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 14,
                'status' => 1,
                'created_at' => '2021-11-09 11:22:33',
                'updated_at' => '2021-11-09 11:22:33',
            ],
            [
                'id' => 61,
                'name' => 'Apple Italia',
                'thumbnail' => 'fruits-8.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 30,
                'status' => 1,
                'created_at' => '2021-11-12 11:11:33',
                'updated_at' => '2021-11-12 11:11:33',
            ],
            [
                'id' => 62,
                'name' => 'Apple Thailand',
                'thumbnail' => 'fruits-9.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 18,
                'status' => 1,
                'created_at' => '2021-11-12 11:14:33',
                'updated_at' => '2021-11-12 11:14:33',
            ],
            [
                'id' => 63,
                'name' => 'Apple VietNam',
                'thumbnail' => 'fruits-10.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 17,
                'status' => 1,
                'created_at' => '2022-01-12 13:14:33',
                'updated_at' => '2022-01-12 13:14:33',
            ],
            [
                'id' => 64,
                'name' => 'Orange VietNam',
                'thumbnail' => 'fruits-11.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 22,
                'status' => 1,
                'created_at' => '2022-01-13 13:14:33',
                'updated_at' => '2022-01-13 13:14:33',
            ],
            [
                'id' => 65,
                'name' => 'Orange ThaiLand',
                'thumbnail' => 'fruits-12.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 13,
                'status' => 1,
                'created_at' => '2022-01-13 13:39:33',
                'updated_at' => '2022-01-13 13:39:33',
            ],
            [
                'id' => 66,
                'name' => 'Kiwi',
                'thumbnail' => 'fruits-13.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 38,
                'status' => 1,
                'created_at' => '2022-01-13 13:12:33',
                'updated_at' => '2022-01-13 13:12:33',
            ],
            [
                'id' => 67,
                'name' => 'Kiwi Taiwan',
                'thumbnail' => 'fruits-1.jpg',
                'description' => 'Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 12,
                'discount_id' => null,
                'price' => 28,
                'status' => 1,
                'created_at' => '2022-01-13 13:24:33',
                'updated_at' => '2022-01-13 13:24:33',
            ],
            [
                'id' => 69,
                'name' => 'Cabbage',
                'thumbnail' => 'vegetable-20.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 9,
                'status' => 1,
                'created_at' => '2022-01-15 13:11:11',
                'updated_at' => '2022-01-15 13:11:11',
            ],
            [
                'id' => 70,
                'name' => 'Cauliflower',
                'thumbnail' => 'vegetable-22.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 27,
                'status' => 1,
                'created_at' => '2022-02-13 13:11:11',
                'updated_at' => '2022-02-13 13:11:11',
            ],
            [
                'id' => 71,
                'name' => 'Fennel',
                'thumbnail' => 'vegetable-23.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 9,
                'status' => 1,
                'created_at' => '2022-01-18 13:11:11',
                'updated_at' => '2022-01-18 13:11:11',
            ],
            [
                'id' => 72,
                'name' => 'Asparagus',
                'thumbnail' => 'vegetable-23.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 14,
                'status' => 1,
                'created_at' => '2022-01-13 13:31:11',
                'updated_at' => '2022-01-13 13:31:11',
            ],
            [
                'id' => 73,
                'name' => 'Broccoli',
                'thumbnail' => 'vegetable-24.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 13,
                'status' => 1,
                'created_at' => '2022-01-13 13:21:11',
                'updated_at' => '2022-01-13 13:21:11',
            ],
            [
                'id' => 74,
                'name' => 'Horseradish',
                'thumbnail' => 'vegetable-26.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 26,
                'status' => 1,
                'created_at' => '2022-01-21 21:11:11',
                'updated_at' => '2022-01-21 21:11:11',
            ],
            [
                'id' => 75,
                'name' => 'Lettuce',
                'thumbnail' => 'vegetable-27.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 19,
                'status' => 1,
                'created_at' => '2022-01-13 13:11:32',
                'updated_at' => '2022-01-13 13:11:32',
            ],
            [
                'id' => 76,
                'name' => 'Perilla leaf',
                'thumbnail' => 'vegetable-27.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 5,
                'discount_id' => null,
                'price' => 16,
                'status' => 1,
                'created_at' => '2022-01-13 13:24:11',
                'updated_at' => '2022-01-13 13:24:11',
            ],
            [
                'id' => 77,
                'name' => 'Spinach',
                'thumbnail' => 'vegetable-26.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 18,
                'status' => 1,
                'created_at' => '2022-01-19 13:24:11',
                'updated_at' => '2022-01-19 13:24:11',
            ],
            [
                'id' => 78,
                'name' => 'Spinach',
                'thumbnail' => 'vegetable-28.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 22,
                'status' => 1,
                'created_at' => '2022-02-19 13:24:11',
                'updated_at' => '2022-02-19 13:24:11',
            ],
            [
                'id' => 79,
                'name' => 'Wild betel leaves',
                'thumbnail' => 'vegetable-30.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 21,
                'status' => 1,
                'created_at' => '2022-01-19 13:16:11',
                'updated_at' => '2022-01-19 13:16:11',
            ],
            [
                'id' => 80,
                'name' => 'Bean sprouts',
                'thumbnail' => 'vegetable-31.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 30,
                'status' => 1,
                'created_at' => '2022-01-19 13:24:20',
                'updated_at' => '2022-01-19 13:24:20',
            ],
            [
                'id' => 81,
                'name' => 'Green onion',
                'thumbnail' => 'vegetable-32.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 27,
                'status' => 1,
                'created_at' => '2022-01-19 17:24:11',
                'updated_at' => '2022-01-19 17:24:11',
            ],
            [
                'id' => 82,
                'name' => 'Corn',
                'thumbnail' => 'vegetable-33.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 8,
                'status' => 1,
                'created_at' => '2022-01-19 21:24:11',
                'updated_at' => '2022-01-19 21:24:11',
            ],
            [
                'id' => 83,
                'name' => 'Beetroot',
                'thumbnail' => 'vegetable-34.jpg',
                'description' => 'Vegetable, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 6,
                'discount_id' => null,
                'price' => 5,
                'status' => 1,
                'created_at' => '2022-01-19 18:24:11',
                'updated_at' => '2022-01-19 18:24:11',
            ],
            [
                'id' => 84,
                'name' => 'Fruity milk',
                'thumbnail' => 'milk-10.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 37,
                'status' => 1,
                'created_at' => '2022-01-19 18:22:11',
                'updated_at' => '2022-01-19 18:22:11',
            ],
            [
                'id' => 85,
                'name' => 'Peanut milk',
                'thumbnail' => 'milk-11.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 29,
                'status' => 1,
                'created_at' => '2022-01-19 18:24:11',
                'updated_at' => '2022-01-19 18:24:11',
            ],
            [
                'id' => 86,
                'name' => 'Magical Milk',
                'thumbnail' => 'milk-12.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 17,
                'status' => 1,
                'created_at' => '2022-01-19 18:24:14',
                'updated_at' => '2022-01-19 18:24:14',
            ],
            [
                'id' => 87,
                'name' => 'Creamy Milk',
                'thumbnail' => 'milk-13.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 12,
                'status' => 1,
                'created_at' => '2022-01-19 19:24:11',
                'updated_at' => '2022-01-19 19:24:11',
            ],
            [
                'id' => 88,
                'name' => 'Frosted Milk',
                'thumbnail' => 'milk-14.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-01-19 10:24:11',
                'updated_at' => '2022-01-19 10:24:11',
            ],
            [
                'id' => 89,
                'name' => 'Dairy Love milk',
                'thumbnail' => 'milk-15.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 10,
                'status' => 1,
                'created_at' => '2022-01-19 18:20:11',
                'updated_at' => '2022-01-19 18:20:11',
            ],
            [
                'id' => 90,
                'name' => 'Mind-blowing milk',
                'thumbnail' => 'milk-14.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 33,
                'status' => 1,
                'created_at' => '2022-01-19 18:24:22',
                'updated_at' => '2022-01-19 18:24:22',
            ],
            [
                'id' => 91,
                'name' => 'Milk Land',
                'thumbnail' => 'milk-13.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 25,
                'status' => 1,
                'created_at' => '2022-01-19 11:24:11',
                'updated_at' => '2022-01-19 11:24:11',
            ],
            [
                'id' => 92,
                'name' => 'The Milk Truck',
                'thumbnail' => 'milk-12.jpg',
                'description' => 'Milk, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Thus, apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.',
                'category_id' => 13,
                'discount_id' => null,
                'price' => 15,
                'status' => 1,
                'created_at' => '2022-01-19 18:11:11',
                'updated_at' => '2022-01-19 18:11:11',
            ],
        ]);
    }
}
